apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: pf-cluster
  region: ap-northeast-2

nodeGroups:
  - name: ng-1
    instanceType: t3a.large
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
